CI step to check deepcopy is up to date
Signed-off-by: Nicolas De Loof <nicolas.deloof@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,6 +14,13 @@ jobs:
         uses: actions/checkout@v4
       - name: Check license
         run: DOCKER_BUILDKIT=1 make check-license
+      - uses: actions/setup-go@v5
+      - name: Check deepcopy
+        run: |
+          make deepcopy
+          if [ -n "$(git status --porcelain)" ]; then
+            echo >&2 'ERROR: DeepCopy is not up to date with code. Please run "make deepcopy"'
+          fi
 
   test:
     strategy:
